# -*- coding: utf-8 -*-
"""RNN_and_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uee86eJjQ-zUB68r1iask3R_qTaQOQ20
"""

import pandas as pd

# Sample data for sentiment analysis (expanded to at least 150 entries)
text_entries = [
    'I love this product, it\'s amazing!',
    'This is a terrible service, very disappointed.',
    'The movie was great, highly recommend it.',
    'I hate the slow delivery and bad customer support.',
    'Fantastic experience, everything was perfect.',
    'What a waste of time and money, absolutely awful.',
    'Enjoyed every moment of it, a truly wonderful day.',
    'Never buying from them again, poor quality.',
    'Happy with my purchase, good value.',
    'Worst decision ever, regret it completely.',
    'Absolutely wonderful experience, exceeded expectations.',
    'Frustrating and buggy software, needs major improvements.',
    'This book is a masterpiece, a must-read for everyone.',
    'The food was bland and overpriced, very unappetizing.',
    'Highly recommend this hotel, excellent staff and amenities.',
    'My phone broke after a week, cheaply made and unreliable.',
    'Such a peaceful morning, perfect start to the day.',
    'Customer service was rude and unhelpful, shocking.',
    'This concert was electrifying, I had an amazing time!',
    'The product description was misleading, felt scammed.',
    'Thrilled with my new car, smooth ride and stylish design.',
    'The delivery was super late, ruined my plans.',
    'Learning so much from this course, very insightful.',
    'The internet connection is constantly dropping, infuriating.',
    'A truly inspiring speech, left me motivated.',
    'This game is boring and repetitive, a real snooze-fest.',
    'Enjoying my vacation immensely, beautiful scenery.',
    'The repair service was slow and ineffective, still broken.',
    'Excellent quality materials, feels very premium.',
    'Received a damaged item, poor packaging.',
    'So glad I bought this, it\'s incredibly useful.',
    'The restaurant was noisy and cramped, unpleasant atmosphere.',
    'A refreshing new take on an old classic, well done!',
    'Horrible experience with the return policy, very difficult.',
    'This app has made my life so much easier, thank you!',
    'The warranty process is a nightmare, complicated and slow.',
    'The best coffee I\'ve ever tasted, truly exceptional.',
    'My package went missing, no tracking updates.',
    'Always a pleasure visiting this art gallery, so calming.',
    'The movie ended abruptly, felt unfinished.',
    'Unforgettable journey, saw breathtaking sights.',
    'The sound quality is terrible, very distorted.',
    'Such a thoughtful gift, made my day!',
    'Waiting on hold for hours, terrible phone support.',
    'Love the vibrant colors of this painting, so captivating.',
    'The product stopped working after a day, useless.',
    'Feeling so energized after that workout, great gym.',
    'The instructions were unclear, impossible to assemble.',
    'This new update is fantastic, great new features!',
    'My order was incorrect, wrong items received.',
    'A very insightful documentary, learned a lot.',
    'The public transport here is unreliable, always late.',
    'So much fun at the amusement park, thrilling rides!',
    'The rental car was dirty and had a weird smell.',
    'Highly recommend this brand, always reliable products.',
    'The concert tickets were overpriced for the view.',
    'Such a captivating story, couldn\'t put it down.',
    'The flight was delayed by hours, massive inconvenience.',
    'This software saves me so much time, invaluable tool.',
    'The customer support chat is useless, no real help.',
    'What a wonderful performance, truly talented artists.',
    'The battery life of this device is abysmal, dies quickly.',
    'Absolutely delicious meal, perfect blend of flavors.',
    'The online store is clunky and difficult to navigate.',
    'Feeling so relaxed after the spa day, pure bliss.',
    'The service technician never showed up, wasted my day.',
    'This coffee shop has the best atmosphere, cozy and warm.',
    'The parking situation is impossible, always full.',
    'Got a great deal on this, super happy with the price.',
    'The quality of the video streaming is poor, pixelated.',
    'Such a rewarding experience, felt truly accomplished.',
    'My data plan is so slow, frustratingly bad.',
    'The sunrise this morning was absolutely stunning, beautiful.',
    'The product arrived broken, clearly mishandled.',
    'This exercise routine is tough but effective, feeling stronger.',
    'The app crashes constantly, very unstable.',
    'A truly inspiring work of art, thought-provoking.',
    'The shipping costs were exorbitant, shocking.',
    'So happy with the results, exactly what I wanted.',
    'The hotel room smelled damp and moldy, very unpleasant.',
    'The best vacation ever, created lasting memories.',
    'The internet service was down for two days, no explanation.',
    'This course is well-structured and easy to follow.',
    'The bus was overcrowded and uncomfortable, horrible commute.',
    'Found exactly what I needed, great selection.',
    'The sales representative was pushy and annoying.',
    'Such a joyous occasion, filled with laughter.',
    'The package was left at the wrong door, lost it.',
    'Very impressed with the efficiency of this system.',
    'The food arrived cold and soggy, inedible.',
    'An outstanding achievement, truly remarkable.',
    'The instructions were in a foreign language, unreadable.',
    'This makes my daily routine so much smoother, highly recommend.',
    'My account was hacked, no security measures.',
    'The show was spectacular, loved every minute.',
    'The quality of materials is so low, feels cheap.',
    'A perfect evening with good friends, cherished moments.',
    'The product has a major design flaw, impractical.',
    'So grateful for this opportunity, truly a blessing.',
    'The booking system is always buggy, difficult to use.',
    'This workshop was incredibly informative and helpful.',
    'The airline lost my luggage, ruined my trip.',
    'Feeling refreshed and invigorated after this.',
    'The landlord ignored all my repair requests, awful.',
    'Such a clever invention, solves a real problem.',
    'The delivery person was rude and unprofessional.',
    'Truly a five-star experience, impeccable service.',
    'The subscription price keeps increasing, feeling ripped off.',
    'This podcast is so engaging, always look forward to it.',
    'The restaurant gave me food poisoning, very sick.',
    'An amazing view from the top of the mountain, breathtaking.',
    'The product description was inaccurate, disappointed.',
    'So much positive energy in this place, uplifting.',
    'The manager was dismissive and unhelpful.',
    'What a fantastic innovation, truly game-changing.',
    'My appointment was double-booked, wasted my time.',
    'Always a great time at this coffee shop, friendly staff.',
    'The public restrooms were filthy, disgusting.',
    'This recipe turned out perfectly, absolutely delicious.',
    'The taxi driver took the longest route, ripped off.',
    'Such a heartwarming story, brought tears to my eyes.',
    'The software update broke key features, very frustrating.',
    'A powerful performance that moved the entire audience.',
    'The online support takes forever to respond, no help.',
    'My favorite movie of all time, watched it countless times.',
    'The product arrived with missing parts, incomplete.',
    'So happy with this purchase, great value for money.',
    'The waiting room was overcrowded and uncomfortable.',
    'This new feature is incredibly intuitive and useful.',
    'The website is constantly crashing, unreliable.',
    'What a delightful surprise, made my day complete.',
    'The noise level in this office is unbearable, distracting.',
    'A truly magical experience, felt like a dream.',
    'The refund process was slow and complicated, difficult.',
    'This book changed my perspective, highly recommend it.',
    'The delivery driver was exceptionally polite and helpful.',
    'The quality of the garment is very poor, falling apart.',
    'An inspiring leader who motivates everyone around them.',
    'The customer service was non-existent, no support.',
    'This game is so addictive, can\'t stop playing!',
    'The product broke within a month, very disappointed.',
    'Feeling completely satisfied with the outcome.',
    'The installation process was complicated and confusing.',
    'Such a vibrant atmosphere, full of life and energy.',
    'The cost of repairs was astronomical, felt cheated.',
    'A brilliant solution to a complex problem, well done!',
    'The server is always down, very frustrating.',
    'This concert was a blast, danced all night long!',
    'The food was stale and tasteless, wasted my money.',
    'So grateful for the prompt assistance, truly helpful.',
    'The website design is awful, hard to find anything.',
    'What a refreshing change of pace, much needed.',
    'My order was canceled without explanation, annoying.',
    'This documentary was truly eye-opening, learned a lot.',
    'The service was incredibly slow, took forever.',
    'A perfect blend of comfort and style, love it!',
    'The car rental agency was a nightmare to deal with.',
    'Such a talented artist, their work is mesmerizing.',
    'The product is defective, doesn\'t work as advertised.',
    'Feeling incredibly optimistic about the future, hopeful.',
    'The return shipping costs were excessive, unfair.',
    'This class is so engaging and interactive, learning a ton.',
    'The plumbing issue is still not fixed, incompetent.',
    'A truly unforgettable performance, left me speechless.',
    'The internet speed is excruciatingly slow, unbearable.',
    'So happy with how this project turned out, proud.',
    'The wait time for support is ridiculous, hours long.',
    'This restaurant has the best ambiance, very romantic.',
    'The quality control is terrible, many defects.',
    'An absolutely amazing piece of technology, revolutionary.',
    'My subscription was automatically renewed without consent.',
    'What a wonderful community spirit, so supportive.',
    'The repair shop overcharged me, felt scammed.',
    'This new feature is a game-changer, so convenient.',
    'The package arrived severely damaged, broken items.',
    'Feeling very grateful for all the help received.',
    'The app is full of ads and bugs, very annoying.',
    'A truly inspiring book that everyone should read.',
    'The movie was so boring, I fell asleep.',
    'So much fun exploring this new city, exciting adventure.',
    'The refund never processed, still waiting.',
    'This tea tastes absolutely divine, so soothing.',
    'The customer service agent was very rude and unhelpful.'
]

# Generate sentiment labels to match the length of text_entries
sentiment_labels = ['positive' if i % 2 == 0 else 'negative' for i in range(len(text_entries))]

data = {
    'text': text_entries,
    'sentiment': sentiment_labels
}

df = pd.DataFrame(data)
display(df.head())

df['sentiment'].unique()

from typing import Sequence
from IPython.core.displayhook import tokenize
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Dense, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping

#1.


#initialize tokenizer(creating objects)
#2.num_words =Maximum no. of words to keep
#3.oov_ token = a token to replace out of vocabulary

tokenizer = Tokenizer(num_words=100,oov_token='<unk>')

#fit on text column
tokenizer.fit_on_texts(df['text'])


#convert the text into sequence of integer
sequences = tokenizer.texts_to_sequences(df['text'])

#padding sequences to avoid non uniform length
max_sequence_len = max([len(i) for i in sequences])
padded_sequences= pad_sequences(sequences, maxlen= max_sequence_len)

from sklearn.preprocessing import LabelEncoder
label_encoder  = LabelEncoder()
labels = label_encoder.fit_transform(df['sentiment'])

vocab_size = len(tokenizer.word_index) + 1 #+1 for oov
embedding_dim =16 #dimension of the words embeddings
from tensorflow.keras.layers import Embedding, SimpleRNN, LSTM,Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.callbacks import EarlyStopping


rnn_model = Sequential(
    [
          Embedding(vocab_size,embedding_dim),
          SimpleRNN(32),
          Dense(1,activation='sigmoid') #output layer 1

    ]
)

rnn_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
early_stopping = EarlyStopping(monitor='val_loss',patience=3)
rnn_model.fit(padded_sequences,labels,epochs=30,callbacks=[early_stopping],validation_split=0.2)

lstm_model = Sequential(
    [
          Embedding(vocab_size,embedding_dim),
          SimpleRNN(32),
          Dense(1,activation='sigmoid') #output layer 1

    ]
)

lstm_model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
early_stopping = EarlyStopping(monitor='val_loss',patience=3)
lstm_model.fit(padded_sequences,labels,epochs=30,callbacks=[early_stopping],validation_split=0.2)

#evaluation
rnn_model.evaluate(padded_sequences,labels)

lstm_model.evaluate(padded_sequences,labels)

